export const Goodbyeinenglish = [
    "goodbye",
    "bye",
    "bye for now",
    "bye for now!",
    "see you!",
    "see you",
    "see ya",
    "see you soon!",
    "see you soon",
    "see ya soon",
    "see you later!",
    "see you later",
    "talk to you later!",
    "talk to you later",
    "catch up with you later",
    "i hope to see you soon",
    "see you next time",
    "i’m looking forward to seeing you soon",
    "it was nice meeting you",
    "it’s been really nice knowing you",
    "it has been a pleasure, we’ll speak soon",
    "it has been a pleasure we’ll speak soon",
    "it was really great to see you, catch you later",
    "it was really great to see you catch you later",
    "all the best, bye",
    "take care!",
    "take care!!",
    "take care!!",
    "take care",
    "stay in touch.",
    "i’m really going to miss you.",
    "i’ve got to go now.",
];
