
export const Thankyouinenglish = [

    "thank you",
    "thanks",
    "thank you very much",
    "thanks a lot",
    "thanks a lot!",
    "tany thanks",
    "sincerely thanks",
    "thank you so much",
    "thank you so much!",
    "thanks a million for your help",
    "i really appreciate your help",
    "you are so kind",
    "i don’t know how to express my thanks",
    "there are no words to show my appreciation!",
    "there are no words to show my appreciation",
    "what you’ve done means a lot to me",
    "that’s so kind of you",
    "you’ve made my day",
    "i owe you a great deal",
    "thank you from the bottom of my heart for everything",
    "how can I ever possibly thank you?",
    "how can I ever possibly thank you",
    "you’re welcome!",
    "you’re welcome!!",
    "you’re welcome!!!",
    "you’re welcome",
    "it was my pleasure",
    "my pleasure",
    "don’t mention it",
    "forget it",
    "no big deal",
    "it’s was nothing",
    "think nothing of it",
    "i’m glad that I can help you",
]
 

